### ISSUE TITLE
Battery optimization warning 

### ISSUE THREAD

**Issue by gpion** [smrtprjcts/atvnotif#2]
On my TV the app displays that warning : 
![20240121_092451 2.jpg](https://github.com/smrtprjcts/atvnotif/assets/2971216/f87708ce-c514-4612-ae25-b41a41277edb)

Activating "OK" opens Google TV settings main menu.

I've managed to pair anyway but sending a test notification fails
![Screenshot_20240121_092744_Android TV Notifier.png](https://github.com/smrtprjcts/atvnotif/assets/2971216/ef8703bb-572a-4680-9ce1-fb256bc82aac)

**Comment by smrtprjcts** [comment]
1. 
It's not possible to move to proper battery settings on Android TV as on phones. :(
You can find it as it wrote. That's why I put  the description into the dialog.

2.
Is there still the same IP as you paired or it was paired too long and IP has changed?

**Comment by smrtprjcts** [comment]
1. 
It's not possible to move to proper battery settings on Android TV as on phones. :(
You can find it as it wrote. That's why I put  the suggestion/description into the dialog.

2.
a, Has the IP changed since you paired?
b, More possible that the app is not running on the TV because you have not granted the battery permission and the TV killed the app in the background.
You can try it if you open the app on TV. If it's working then you have to grant the permission for stable working.

**Comment by gpion** [comment]
> It's not possible to move to proper battery settings on Android TV as on phones. :(
> You can find it as it wrote. That's why I put the suggestion/description into the dialog.

Not sure I correctly understand. In the code you can't post the battery popup warning only when running on ^phone or tablet?

> is there still the same IP as you paired or it was paired too long and IP has changed?

Yes, same phone and same IP. Was already paired since several weeks. Happens after latest update.
Since it's now fixed after resetting the app on TV side and redoing the pairing process I'm not able to reproduce the issue.

**Comment by smrtprjcts** [comment]
> > It's not possible to move to proper battery settings on Android TV as on phones. :(
> > You can find it as it wrote. That's why I put the suggestion/description into the dialog.
> 
> Not sure I correctly understand. In the code you can't post the battery popup warning only when running on ^phone or tablet?
> 
>
Yes. You can manually find and  the battery settings in the main settings of the tv. On my tv: Settings -> Apps -> Special App Permissions -> Energy Optimization

> > is there still the same IP as you paired or it was paired too long and IP has changed?
> 
> Yes, same phone and same IP. Was already paired since several weeks. Happens after latest update.
> Since it's now fixed after resetting the app on TV side and redoing the pairing process I'm not able to reproduce the issue.
> 
> 
>

Okay, it solves the problem but I guess that the problem is the battery optimization. You should grant it for proper, stable working.

**Comment by gpion** [comment]
>> You can manually find and the battery settings in the main settings of the tv. On my tv: Settings -> Apps -> Special App Permissions -> Energy Optimization
>
>Found it, now unchecked and no warning anymore.

Super. I hope it solves your problem.

>I didn't imagine that that kind of settings were available on Google/Android TV (as in Smartphones where it makes more sense)

Me neither. But the Android/Google TV system work the same way as the phone system and kill/restrict applications in the background.
